name: reusable

on: 
  workflow_dispatch:
    inputs:
      name: 
        default: 'default name'
    secrets: 
      access-token:
        default: 'default access token'
        type: string
        required: true
        
  workflow_call:
    inputs:
      name:
        description: "who"
        type: string
        default: 'mallen'
        required: true

    secrets:
      access-token:
        description: 'secret'
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: |
          ls -la

  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: display github context
        run: |
          echo '${{ toJson(github) }}'
      - name: display input name
        run: |
          echo "inputs.name: ${{ inputs.name }}"
      - name: display access token
        run: |
          echo "access token: ${{ secrets.access-token }}"