name: reusable

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: "Name input"
        default: 'default name'
        
    secrets:
      access-token:
        description: 'secret'
        required: true
        
workflow_call:
    inputs:
      name:
        description: "who"
        type: string
        default: 'mallen'
        required: true

    secrets:
      access-token:
        description: 'secret'
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: |
          ls -la

  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: display github context
        run: |
          echo '${{ toJson(github) }}'
      - name: display input name
        run: |
          echo "inputs.name: ${{ inputs.name }}"
      - name: display access token
        run: |
          echo "access token: ${{ secrets.access-token }}"